services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres/Dockerfile
    image: dss-postgres
    container_name: dss-postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - PGPASSWORD=postgres12345
      - POSTGRES_DB=dsdojo_db
      - DATABASE_HOST=localhost
    volumes:
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./docker/work/data
        target: /tmp/data

  notebook:
    build:
      context: .
      dockerfile: dockerfiles/notebook/Dockerfile
    image: dss-notebook
    container_name: dss-notebook
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=padawan
      - PG_PASSWORD=padawan12345
      - PG_DATABASE=dsdojo_db
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./docker/doc
        target: /home/jovyan/doc
      - type: bind
        source: ./docker/work
        target: /home/jovyan/work
      - type: bind
        source: ./docker/.jupyter/jupyter_lab_config.py
        target: /home/jovyan/.jupyter/jupyter_lab_config.py
    command: start-notebook.sh --NotebookApp.token=''
